### PR TITLE
Hapi v17 support

### PR DESCRIPTION
**Pull request by robman87**
Maybe publish to NPM as version compatible with Hapi >= 17?

### CODE REVIEW

**Comment by chamini2** [comment]
Now please rebase from `master` and we can review these changes!

**Comment by abramenal** [comment]
Hi @robman87, do you need any help moving this to the finish line?

**Comment by robman87** [comment]
@abramenal Thanks for offering help. I think it should be working now. @chamini2, can we review changes?

**Comment by robman87** [comment]
@abramenal Thanks for offering help. I think it should be working now. @chamini2, can we review changes?

**Comment by chamini2** [comment]
@robman87, please rebase or merge master so we don't have conflicts.

**Comment by robman87** [comment]
I tried remaking the changes from merged master and submit as a new pull request #4 , but it still has conflicts.

**Comment by robman87** [comment]
I see what I did wrong, I never merged your latest master to my forked master before making #4

**Comment by robman87** [comment]
Ok, finally I managed to merge your master to my master. This must be the ugliest merges I have made. Lets continue in #4

**Pull request closed without merging**
